<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * Cats Account Model *  @package		Rookie
 * @subpackage	Models
 * @category	Company
 * @author		Prabhakar Ram
 * @website		http://www.onlienprabhakar.com
 * @company     Tekshapers Inc
 * @since		Version 1.0
 */
 
class Supplier_China_mod extends CI_Model {

   // public $table     = "companies";
	public $per_page  = "per_page";
    var $table = "supplier_china";
    var $assign_leads = "assign_leads";
    var $assign_product = "assign_product";
    var $lead_reminder = "lead_reminder";
    var $follow_ups = "follow_ups";
    var $contacts = "contacts";
    var $lead_others = "lead_others";
    var $disqualify_leads = "disqualify_leads";
    var $company = "company";
    var $company_contacts = "supplier_china_contact";
    var $lead_notes = "supplier_china_notes";
    var $users = "users";
    var $referral_source = "referral_source";
    /**
	 * Constructor
	 */     
    function __construct()
    {
        parent::__construct();
    }
    
    // ------------------------------------------------------------------------

    /**
     * Add Company
     *
     * This function Add Company
     * 
     * @access	public
     * @return	mixed Array 
     */     
    function add()
    {
        //pr("siihfcoidh");die;
        $this->form_validation->set_rules('name', lang('name'), 'trim|required');
		//$this->form_validation->set_rules('country', lang('country'), "trim|required");
	    $this->form_validation->set_rules('state_comp', lang('state'), 'trim|required');
		$this->form_validation->set_rules('city_comp', lang('city'), "trim|required");
		 $this->form_validation->set_rules('city_code', lang('city_code'), 'trim|required');
		$this->form_validation->set_rules('pincode', lang('pincode'), "trim|required");
		 //$this->form_validation->set_rules('type_of_establishment', lang('type_of_establishment'), 'trim|required');
		$this->form_validation->set_rules('website_address', lang('item_service_description'), "trim|required");
		 $this->form_validation->set_rules('item_description', lang('item_description'), 'trim|required');
		
		$this->form_validation->set_rules('bank_name', lang('bank_name'), 'trim|required');
		$this->form_validation->set_rules('account_number', lang('account_number'), "trim|required");
		$this->form_validation->set_rules('tax_no', lang('tax_no'), "trim|required");
		//$this->form_validation->set_rules('vendor_code', lang('vendor_code'), 'trim|required|is_unique[supplier_china.vendor_code]');
        
        if($this->form_validation->run() == FALSE)
        {
            //set_flashdata("error",validation_errors());
            return FALSE;
        } 
       
        $user_id = currentuserinfo()->id;
        
        //$data['vendor_data']           = $this->input->post('vendor_data',TRUE);
        $data['name']           = $this->input->post('name',TRUE);
        $data['vendor_type']        = $this->input->post('vendor_type',TRUE);
		//$data['vendor_code']        = $this->input->post('vendor_code',TRUE);
		$data['address']           = $this->input->post('address',TRUE);
        $data['factory_address']        = $this->input->post('factory_address',TRUE);
		//$data['country']           = $this->input->post('country',TRUE);
        $data['state']        = $this->input->post('state_comp',TRUE);
		$data['city']           = $this->input->post('city_comp',TRUE);
        $data['pincode']        = $this->input->post('pincode',TRUE);
		$data['city_code']           = $this->input->post('city_code',TRUE);
        $data['landline']        = $this->input->post('landline',TRUE);
		//$data['established_year']           = $this->input->post('established_year',TRUE);
        //$data['type_of_establishment']        = $this->input->post('type_of_establishment',TRUE);
		$data['website_address']           = $this->input->post('website_address',TRUE);
        $data['item_description']        = $this->input->post('item_description',TRUE);
		
		$data['tax_no']           = $this->input->post('tax_no',TRUE);
		$data['bank_name']           = $this->input->post('bank_name',TRUE);
        $data['account_number']        = $this->input->post('account_number',TRUE);
		//$data['account_type']           = $this->input->post('account_type',TRUE);
        $data['bank_address']        = $this->input->post('bank_address',TRUE);
       
        //pr($data);die;
        set_common_insert_value();        
        $this->db->insert($this->table,$data);           
        $id = $this->db->insert_id();
		//vendor code autogenerated
		$pattern = "CH0000";
		$auto['vendor_code']              = $pattern.$id;
		$this->db->where("id",$id);
		$this->db->update($this->table,$auto);  
		$company_doc = [];
        if(isset($_FILES['document']) && !empty($_FILES['document']['name']))
        {
            
            foreach ($_FILES['document']['name'] as $document_key => $document_value) {
                $_FILES['document_file']['name']     = $_FILES['document']['name'][$document_key];
                $_FILES['document_file']['type']     = $_FILES['document']['type'][$document_key];
                $_FILES['document_file']['tmp_name'] = $_FILES['document']['tmp_name'][$document_key];
                $_FILES['document_file']['error']    = $_FILES['document']['error'][$document_key];
                $_FILES['document_file']['size']     = $_FILES['document']['size'][$document_key];
                $fileData=$this->uploadDoc($_FILES['document_file']);
                
                if(isset($fileData['success'])){
                    $company_doc[$document_key]['filename']     = $fileData['success']['file_name'];   
                    $company_doc[$document_key]['supplier_id']   = $id;   
                }
            }
            if(!empty($company_doc))
            {
                $this->db->insert_batch('supplier_china_doc', $company_doc);
            }
        }
		$note = $_POST['note'];
          if($note){
                $noteArray=array(
                  'supplier_id'=>$id,
                  'added_by'=>$user_id,
                  'note'=>$note,
                  'created'=>date_time(),
                  'modified'=>date_time()
                );
            // pr($noteArray);
		$inser_id=$this->db->insert('supplier_china_notes',$noteArray);
		  }
		   if ($this->db->trans_status() === false) {
                $this->db->trans_rollback();
            } else {
                $this->db->trans_commit();
			}

        add_report($id);
        
        set_flashdata("success",lang('success'));
        return $id;
    }
    
    // ------------------------------------------------------------------------

    /**
     * Get Company
     *
     * This function Get Company search by company id
     * 
     * @access	public
     * @return	Object 
     */     
    function get($id = NULL)
    {  
        filter_data('sup');
        
        $this->db->select('sup.*,sup.name as vendor_names,sup.address as vendor_address,sup.state as state_id,sic.*,sin.*,st.id as state_id,st.state_name,ct.id as city_id,ct.city_name,dept.name as department_name,desg.name as designation_name');
		$this->db->from('supplier_china sup');
		$this->db->join("states st" , 'st.id=sup.state','left');
		$this->db->join("cities ct" , 'ct.state_id=st.id','left');
		$this->db->join('supplier_china_contact sic','sup.id=sic.supplier_id','left');
        $this->db->join('supplier_china_notes sin','sup.id=sin.supplier_id','left');
        $this->db->join('department dept','sic.department=dept.id','left');
        $this->db->join('designation desg','sic.designation=desg.id','left');
		//$this->db->join("industry in" , 'c.industry=in.id');
		$this->db->where('sup.id',$id);
        $query = $this->db->get();
        //pr($this->db->last_query());die;
        if($query->num_rows() > 0)
           $query = $query->row();
		$this->db->select('*');
        $this->db->where('supplier_id', $id);
        $company_doc = $this->db->get("supplier_china_doc")->result();
        @$query->company_doc  =   $company_doc;
		
		return $query;
    }
    
    
    
    // ------------------------------------------------------------------------ // ------------------------------------------------------------------------


	function get_notes($id = NULL)
    {
		//pr($id);die;
		
        $this->db->select("supplier_china_notes.*,users.first_name,users.last_name");
		$this->db->join('users','users.id =supplier_china_notes.added_by');
		$this->db->from("supplier_china_notes");
		$this->db->where('supplier_china_notes.supplier_id',$id);
		$this->db->order_by("note","desc");
		$result = $this->db->get();
		if ($result->num_rows > 0) {
            return $result->result();
        } else {
            return false;
        }
    }
    /**
     * Get Industry
     *
     * This function Get ALL Industry 
     * 
     * @access	public
     * @return	Object 
     */     
    function get_industry()
    {  
        //filter_data($this->table);
        //$this->db->where('id',$id);
		$this->db->select("id,name");
		$this->db->order_by("id","desc");
        $query = $this->db->get("industry");
        
        if($query->num_rows() > 0)
           return $query->result();
           
        show_404();
    }
    
    
    
    // ------------------------------------------------------------------------

    /**
     * Get Ajax Companies
     *
     * This function Get Companies with Search and offset functions 
     * 
     * @access	public
     * @return	Object 
     */     
    function ajax_list_items($text, $limit, $offset, $order_by='id', $order='desc',$user='',$is_export=false, $items_data = NULL) {
        $offset = ($offset - 1) * $limit;

        if($is_export==false)
        {
            $this->db->limit($limit, $offset);
        }
        if($is_export==true &&  !empty($items_data))
        {
            $this->db->where_in("$this->table.id", $items_data);
        }
        $text=strtolower(trim($text));

        if($text) {
            // $this->db->like("$this->table.*",$text);
            $this->db->like("CONCAT(sup.name,sup.vendor_code,ct.city_name,st.state_name,co.name)",$text);
        }

        if($order_by && $order)
            $this->db->order_by($order_by, $order);

      //$this->db->select("SQL_CALC_FOUND_ROWS $this->table .*",FALSE);
        //$this->db->from("$this->table");
        filter_data('sup');      
        //$query = $this->db->get();
       // pr($query->result());exit;
        //echo $this->db->last_query();exit;
		$this->db->where('sup.status','1');
		$this->db->select('SQL_CALC_FOUND_ROWS sup.*,co.id as vendor_id,co.name as vendor_name,st.id as state_id,st.state_name,ct.id as city_id,ct.city_name',false);
		$this->db->from('supplier_china as sup');
		$this->db->join("supplier_vendor co" , 'co.id=sup.vendor_type',"LEFT");
		$this->db->join("states st" , 'st.id=sup.state','LEFT');
		$this->db->join("cities ct" , 'ct.id=sup.city','LEFT');
		
		$query = $this->db->get();
		// pr($this->db->last_query());die;
		$data['result'] = $query->result();
        $query = $this->db->query('SELECT FOUND_ROWS() AS `count`');

        $data["total"] = $query->row()->count;
        $data['offset'] = $offset;
		//pr($data);die;
        return $data;
    }
    
    
    
    
    //----------------------------------------------------------------------------------
     /**
     * Update Company
     *
     * This function Update Company Name
     * 
     * @access	public
     * @return	int 
     */     
    function update($id = NULL)
    {
		
		 $this->form_validation->set_rules('name', lang('name'), 'trim|required');
		//$this->form_validation->set_rules('country', lang('country'), "trim|required");
	    $this->form_validation->set_rules('state_comp', lang('state'), 'trim|required');
		$this->form_validation->set_rules('city_comp', lang('city'), "trim|required");
		 $this->form_validation->set_rules('city_code', lang('city_code'), 'trim|required');
		$this->form_validation->set_rules('pincode', lang('pincode'), "trim|required");
		 //$this->form_validation->set_rules('type_of_establishment', lang('type_of_establishment'), 'trim|required');
		$this->form_validation->set_rules('website_address', lang('item_service_description'), "trim|required");
		 $this->form_validation->set_rules('item_description', lang('item_description'), 'trim|required');
		
		$this->form_validation->set_rules('bank_name', lang('bank_name'), 'trim|required');
		$this->form_validation->set_rules('account_number', lang('account_number'), "trim|required");
		$this->form_validation->set_rules('tax_no', lang('tax_no'), "trim|required");
		
		
		if($this->form_validation->run() == FALSE)
        {
            //set_flashdata("error",validation_errors());
            return FALSE;
        } 
		
        $user_id = currentuserinfo()->id;
        $data['name']           = $this->input->post('name',TRUE);
        $data['vendor_type']        = $this->input->post('vendor_type',TRUE);
		//$data['vendor_code']        = $this->input->post('vendor_code',TRUE);
		$data['address']           = $this->input->post('address',TRUE);
        $data['factory_address']        = $this->input->post('factory_address',TRUE);
		//$data['country']           = $this->input->post('country',TRUE);
        $data['state']        = $this->input->post('state_comp',TRUE);
		$data['city']           = $this->input->post('city_comp',TRUE);
        $data['pincode']        = $this->input->post('pincode',TRUE);
		$data['city_code']           = $this->input->post('city_code',TRUE);
        $data['landline']        = $this->input->post('landline',TRUE);
		//$data['established_year']           = $this->input->post('established_year',TRUE);
        //$data['type_of_establishment']        = $this->input->post('type_of_establishment',TRUE);
		$data['website_address']           = $this->input->post('website_address',TRUE);
        $data['item_description']        = $this->input->post('item_description',TRUE);
		
		$data['tax_no']           = $this->input->post('tax_no',TRUE);
		$data['bank_name']           = $this->input->post('bank_name',TRUE);
        $data['account_number']        = $this->input->post('account_number',TRUE);
		//$data['account_type']           = $this->input->post('account_type',TRUE);
        $data['bank_address']        = $this->input->post('bank_address',TRUE);
        
        //pr($data);die;
        //$this->db->where("id",$id);
        filter_data();
        set_common_update_value();
		//echo
        $r = $this->db->where("id",$id)->update($this->table,$data);
		//var_dump($r);die;
        $company_doc = [];
        if(isset($_FILES['document']) && !empty($_FILES['document']['name']))
        {
            //pr($_FILES['document']['name']);die;
            foreach ($_FILES['document']['name'] as $document_key => $document_value) {
                $_FILES['document_file']['name']     = $_FILES['document']['name'][$document_key];
                $_FILES['document_file']['type']     = $_FILES['document']['type'][$document_key];
                $_FILES['document_file']['tmp_name'] = $_FILES['document']['tmp_name'][$document_key];
                $_FILES['document_file']['error']    = $_FILES['document']['error'][$document_key];
                $_FILES['document_file']['size']     = $_FILES['document']['size'][$document_key];
                //pr($_FILES['document']['name'][$document_key]);die;
				$fileData=$this->uploadDoc($_FILES['document_file']);
                //pr("yaa");die;
                if(isset($fileData['success'])){
                    $company_doc[$document_key]['filename']     = $fileData['success']['file_name'];   
                    $company_doc[$document_key]['supplier_id']   = $id;   
                }
            }
            //pr($company_doc);die;
            if(!empty($company_doc))
            {
                 $this->db->insert_batch('supplier_china_doc', $company_doc);
            }
        }
		$note = $_POST['note'];
          if($note){
                $noteArray=array(
                  'supplier_id'=>$id,
                  'added_by'=>$user_id,
                  'note'=>$note,
                  'created'=>date_time(),
                  'modified'=>date_time()
                );
           // pr($noteArray);die;
			$inser_id=$this->db->insert('supplier_china_notes',$noteArray);
		  }
        update_report($id);
        
        if($r)
            set_flashdata("success",lang('updated'));
                    
        return $r;
    }
    
   
    function get_flexigrid_cols()  
    {
           $data = array(
            array(
                "display"   =>lang('name'),
                "name"      =>"name",
                "order_by" => "yes"
            ),array(
                "display"   =>'Website Address',
                "name"      =>"website_address",
                "order_by" => "no"
            ),array(
                "display"   =>lang('vendor_type'),
                "name"      =>"vendor_name",
                "order_by" => "yes"
            ),array(
                "display"   =>lang('vendor_address'),
                "name"      =>"address",
                "order_by" => "yes"
            ),array(
                "display"   =>lang('item_service_description'),
                "name"      =>"item_description",
                "order_by" => "yes"
            ),array(
                "display"   =>lang('vendor_code'),
                "name"      =>"vendor_code",
                "order_by" => "yes"
            ),array(
                "display"   =>lang('state'),
                "name"      =>"state_name",
                "order_by" => "yes"
            ),array(
                "display"   =>lang('city'),
                "name"      =>"city_name",
                "order_by" => "yes"
            )
            // ,array(
            //     "display"   =>lang('website'),
            //     "name"      =>"website_address",
            //     "order_by" => "no"
            // )
        );
     
        return $data;       
    }
	//----------------------------------------------------------------------------------
     /**
     * Get  per page listing
     * This function get perpage record in flexigrid     
     * @access	public
     * @return	int 
     */
     
     function perPage($user_id){    		
		$controllerInfo=$this->uri->segment(1)."/".$this->uri->segment(2);
		$this->db->where("action",$controllerInfo);
		$this->db->where("user_id",$user_id);
        $query =$this->db->get($this->per_page);		
		if($query->num_rows >0){
			return $query->row()->records;
		}else{
			return false;
		}
     }

	 // ------------------------------------------------------------------------

	 /**
	 * @function Name   update()
	 * @purpose         to update a record 
	 * @return			boolean
	 * @created         2 May 2013
	 */
 
    function update_perPage($array,$userId){	
        $controllerInfo=$this->uri->segment(1)."/".$this->uri->segment(2);
		$where="action = '$controllerInfo' AND user_id = $userId";
		$query=$this->db->update_string($this->per_page,$array,$where); 
		$result=$this->db->query($query);
		if($result){			
			return true;
		}else{			
			return false;
		}	
    }

	// ------------------------------------------------------------------------

	 /**
	 * @function Name   update()
	 * @purpose         to update a record 
	 * @return			boolean
	 * @created         2 May 2013
	 */
 
    function insert_perPage($array){		
		$query=$this->db->insert_string($this->per_page,$array); 
		$result=$this->db->query($query);
		if($result){			
			return true;
		}else{			
			return false;
		}	
    }
	
	/**
	 * @function Name   export()
	 * @purpose         to export a record 
	 * @return			boolean
	 * @created         2 Aug 2013
	 */
	function export(){
        $items          =$this->input->get_post('items',TRUE);
        $items_data     = str_replace("row","",$items);       
        $items_data      = explode(",",$items_data);

        $this->db->select('sup.*,co.id as vendor_id,co.name as vendor_name,st.id as state_id,st.state_name,ct.id as city_id,ct.city_name');
        $this->db->from('supplier_china as sup');
        $this->db->join("supplier_vendor co" , 'co.id=sup.vendor_type',"left");
        $this->db->join("states st" , 'st.id=sup.state');
        $this->db->join("cities ct" , 'ct.id=sup.city');
       if(!empty($items)){ 
             $this->db->where_in("sup.id",$items_data);
        }
    
    $query = $this->db->get();

    $data= $query->result();  
    //pr($data);die;
    return $data;
  }
    
	
	function fetch_state($country_id){
       
	   if(!empty($country_id)){
		   $country_ids=explode(',',$country_id);
	   }
        $this->db->where_in('country_id', $country_ids);
		$this->db->where('status','1');
        $this->db->order_by('state_name', 'ASC');
        $query = $this->db->get('states');
		//echo $this->db->last_query();die;
        if($query->num_rows()>0){
        $output = '';
        foreach($query->result() as $row){
           // pr($row);die;
		    $output .= '<option value="">Select</option>';
            $output .= '<option value="'.$row->id.'">'.$row->state_name.'</option>';
        }
        //pr($output);die;
		}else{
			$output .= '<option value="">No state found</option>';
		}
        return $output;
    }
	
	// fetch the city according to country
	
	function fetch_city($state_id){
       
	   if(!empty($state_id)){
		   $state_ids=explode(',',$state_id);
	   }
        $this->db->where_in('state_id', $state_ids);
		$this->db->where('status','1');
        $this->db->order_by('city_name', 'ASC');
        $query = $this->db->get('cities');
		//echo $this->db->last_query();die;
        if($query->num_rows()>0){
        $output = '';
		$output .= '<option value="">Select</option>';
        foreach($query->result() as $row){
            //pr($row);die;
			
            $output .= '<option value="'.$row->id.'">'.$row->city_name.'</option>';
        }
        }else{
			$output .= '<option value="">No city found</option>';
		}
        return $output;
    }
	
	public function get_vendor(){
		$this->db->select("id,name");
		$this->db->order_by("name","asc");
		$this->db->where_in('country','2');
		$this->db->where_in('status','1');
        $query = $this->db->get("supplier_vendor");
        
        if($query->num_rows() > 0)
           return $query->result();
           
	}
	public function get_china_state(){
		$this->db->select("states.*,countries.country_name");
		$this->db->join('countries','countries.id=states.country_id');
		$this->db->from("states");
		$this->db->order_by("state_name","asc");
		//$this->db->where_in('country_id','3');
        $query = $this->db->get();
        
        if($query->num_rows() > 0)
           return $query->result();
           
	}
	
	public function check_vendor_code_existance($vendor_code) {
        //$database=DEFAULT_DATABASE;
        $query=$this->db->query("SELECT id FROM supplier_china WHERE vendor_code='$vendor_code'");
        $count=$query->num_rows(); 
        if ($count > 0)
            return true;
    }

    function uploadDoc($file_arr) {
		
		if (@$file_arr['name'] != '') {
			
			$path = $file_arr['name'];
            $ext = pathinfo($path, PATHINFO_EXTENSION);
            $name = md5(time());
            $file_name = $name . "." . $ext;
			$folder_doc = './upload/supplier_china/';
			if (!file_exists($folder_doc)) {
				mkdir($folder_doc, 0777, true);
			}
			$file_arr['name'] 			= $file_name;
		    $config['upload_path'] 		= $folder_doc;
		    $config['allowed_types'] 	= check_file_extension();
		    $config['max_size'] 		= '5000';
		    $config['encrypt_name'] 	= false;
		    $config['remove_spaces'] 	= true;
		    $config['overwrite'] 		= false;
		    $this->load->library('upload');
		    $this->upload->initialize($config);
		    $data=array();
		    if (!$this->upload->do_upload('document_file'))
		    {
		        $data['error'] = $this->upload->display_errors();
		    } else
		    {
		        $data['success'] = $this->upload->data();
		    }
		    return $data;
		}
    }
	
	public function get_table_name(){
		$this->db->where('is_deleted','1');
        $this->db->select("*");
		$result = $this->db->get('inch_form');
        if ($result->num_rows > 0) {
            return $result->result();
        }
    }
    
	 public function delete()
    {
	   $data['status'] = '2';
	   
	   $items           = $this->input->get_post('items',TRUE);
       $items_data      = str_replace("row","",$items);       
       $items_data      = explode(",",$items_data);      
       
       $this->db->where_in("id",$items_data);
       set_common_update_value();
	   $this->db->update('supplier_china',$data);
	   
    }
   
}